# -*- coding: utf-8 -*-
"""admin_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kL48zJMZD2sqabS-FeKumgjGmbYXeYY
"""

import streamlit as st
import requests
from datetime import datetime
import os
import io

# Backend URL
BACKEND_URL = "https://ai-equity-analyst.onrender.com"

st.title("📤 Admin Panel - Upload Documents")

# Upload Form
company_name = st.sidebar.text_input("Company Name")
document_date = st.sidebar.date_input("Document Date")
document_type = st.sidebar.selectbox("Document Type", [
    "Annual Report", "Earnings Call Transcript", "Investor Presentation", "Analyst Call Transcript"
])
uploaded_files = st.sidebar.file_uploader("Upload PDF Files", type=["pdf"], accept_multiple_files=True)

if st.sidebar.button("Upload Files"):
    if uploaded_files and company_name and document_date and document_type:
        for uploaded_file in uploaded_files:
            files = {"file": (uploaded_file.name, uploaded_file.getvalue(), "application/pdf")}
            data = {
                "company_name": company_name,
                "document_date": document_date.strftime("%Y-%m-%d"),
                "document_type": document_type,
            }
            response = requests.post(f"{BACKEND_URL}/upload/", files=files, data=data)

            if response.status_code == 200:
                st.sidebar.success(f"✅ {uploaded_file.name} uploaded successfully!")
            else:
                st.sidebar.error(f"❌ Upload failed for {uploaded_file.name}: {response.text}")
    else:
        st.sidebar.warning("⚠️ Fill all fields & upload at least one file.")

# 🔹 Disclaimer Section
st.markdown("---")
st.markdown(
    """
    ### ⚠️ Disclaimer:
    This platform allows uploading multiple financial documents for AI-based analysis.
    Please ensure that all uploaded files are relevant and accurate.
    """
)